[project]
name = "ai4hws-ex14"
version = "0.1.0"
description = ""
authors = [
    {name = "Anna Buch", email = "anna.buch@tu-berlin.de"},
]
requires-python = ">=3.12"
readme = "README.md"

dependencies = [
    "pandas==2.2.3",
    "tqdm>=4.67.3",
    "torchvision>=0.25.0",
    "webp>=0.4.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "langchain-docling>=2.0.0",
    "spacy>=3.8.11",
    "numpy>=2.5.2",
    "ipykernel>=7.3.0",
    "langgraph>=1.2.11",
    "langchain-nvidia-ai-endpoints>=1.4.3",
    "langchain>=1.3.15",
    "python-dotenv>=1.2.3",
    "requests-mock>=1.12.1",
    "ipytest>=0.14.2",
]

[tool.ruff]
line-length = 120
exclude = [".venv", "versioneer.py", "*_cache"] # keep formating ".ipynb"

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
# see, https://docs.astral.sh/ruff/rules
select = [
    # defaults
    "F",    # Pyflakes
    "E",    # pycodestyle Error


    # additional
    "A",    # not shadow built-in functions
    "I",    # isort imports
    "N",    # check for PEP8 naming conventions
    "W",    # pycodestyle Warning

    # clean docstrings
    "D201", "D207", "D208", "D209", "D210", "D214", "D215", "D300", "D403",

    # auto-remove unused 'noqa' comments
    "RUF100", "RUF101",
]
ignore = ["C901", "E714", "I001"]
exclude = [".ipynb"]
fixable = ["ALL"]

[tool.uv.sources]
py-banshee = { git = "https://github.com/mike-mendoza/py_banshee" }



