name: Build and Testing

on:
  # NOTE: BEST PRACTICE: Run CI on pushes to all branches, except main and branches for fixing bugs and run CI only on pull requests to the main branch
  # HOWEVER, in this example we are doing GitHub Actions on pushes to the main branch (for sake of simplicity and laziness) ;)
  push:
      branches:
      - "**" # matches every branch
  pull_request:
      branches:
      - main

  ## Example (for best practice):
  # push:
  #   branches:
  #   - "**" # matches every branch
  #   - "!main" # except main and branches for fixing bugs
  #   - "!fix-**"
  # pull_request:
  #   branches:
  #   - main

# define 3 jobs [actionlint, build, coverage]
jobs:

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
        
  build:
    strategy:
      #fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Runs on "${{matrix.os}}"
    # define steps of job "build"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Set up uv (latest version)
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d 
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    - name: Set up Python, using version defined in pyproject.toml
      uses: actions/setup-python@v7
      with:
        python-version-file: "pyproject.toml"
    # test to install packages using uv
    - name: Install packages via uv
      run: |
        pip install uv
        uv build
        echo installed packages via uv, using universal/cross-platform dependencies

  coverage:
    name: Coverage Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Set up uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    - name: Run Python tests [pytest]
      working-directory: ./tests
      run: |
        uv run python -m pytest ./src/test_*.py
        echo checking for test errors in ./tests/src/test_*.py